apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 300
      template:
        spec:
          securityContext:
            runAsNonRoot: true
          containers:
            - name: {{ .Values.containerName }}
              imagePullPolicy: Always
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              envFrom:
                - secretRef:
                    name: {{ .Values.db.pass.secretName }}
                - configMapRef:
                    name: {{ .Release.Name }}-configmap
              volumeMounts:
              - name: input-file
                mountPath: /tmp
                readOnly: true
              securityContext:
                runAsUser: 1000
          imagePullSecrets:
          - name: {{ .Values.image.dockerKeySecret }}
          volumes:
            - name: input-file
              configMap:
                name: {{ .Release.Name }}-configmap
                items:
                - key: commands
                  path: "input_file"
          terminationGracePeriodSeconds: 5
          restartPolicy: OnFailure
