---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  database_url: "{{ .Values.db.serviceUrl }}"
  port: "{{ .Values.db.port }}"
  db_name: {{ .Values.db.name }}
  db_user: {{ .Values.db.user }}
  commands: |+
    {{ .Values.commands }}
  input_file: /tmp/input_file
